baseurl: 'neqsoft.com/'
permalink: pretty
title: 'neqsoft'

homepage:
  show_call_box: false

logo:
  mobile: "images/logo/logo.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "36px"

footer:
  copyright_text: 'neqsoft.com @ All rights reserver'

seo:
  meta_og_title: "neqsoft"
  meta_og_type: "website"
  meta_og_url: "https://neqsoft.com"
  meta_og_description: "neqsoft is a single person freelance company focusing on native iOS, Android, backend, database software developmnet and consultancy"
  meta_twitter_card: "summary"
  meta_twitter_site: "@neqsoft"
  meta_twitter_creator: "@neqsoft"

collections:
  services:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables